server:
  port: 9103

spring:
  application:
    name: sc-eureka-server

eureka:
  environment: dev
  instance:
    hostname: sc-eureka-server-node3
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    registry-fetch-interval-seconds: 30
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://sc-eureka-server-node1:9101/eureka/,http://sc-eureka-server-node2:9102/eureka/

